### ISSUE TITLE
F# implementation uses float64 while others use float32

### ISSUE THREAD

**Issue by ForNeVeR** [athas/raytracers#14]
F# has this (rather unfortunate and frustrating, I agree!) "feature": `float` is **the same** as `double` aka `float64`; real analog to `float` from other languages would be `float32`.

I was able to make F# code faster by about 25% by replacing `float` with `float32` (and tuning all the number constants to use `f` suffix, and also `Math` → `MathF`). Probably worth to fix :)

**Comment by athas** [comment]
All of the ML implementations use double precision, because at least Standard ML and OCaml make it hard to do anything else.  I thought it wouldn't have much effect on performance on a CPU, but looks like I was wrong, at least for F#.  Perhaps it's because a single-precision float can be packed into a pointer, and thus we avoid a few heap allocations?  I'll see about fixing it.

**Comment by llelf** [comment]
Shouldn't all implementations be using float64?  It's not fair otherwise.

**Comment by athas** [comment]
The point here isn't fairness, it's to see how straightforward it is to write a pretty simple parallel ray tracer, which used single precision floats in its original formulation.  If the language makes it hard to use single precision, well, that's no different from the language making it hard to use parallelism.  Although the comparison would certainly be less *interesting* if the use of float precision was the dominating factor, I don't think that's the case.  OCaml is very fast and it uses doubles.

**Comment by ForNeVeR** [comment]
Thanks!

I just wanted to note that I understand and respect your position on these benchmarks (i.e. that this is supposed to be opinionated testing with care about code idiomaticity, so not _any_ change that makes the code faster should be applied).

**Comment by llelf** [comment]
> use of float precision was the dominating factor

@athas It's still pretty significant.  But I see your point.

**Comment by athas** [comment]
I have yet to reject any improvements, and I don't know where I'd draw the line.  Probably I don't want anything that causes the programs to stop feeling like *functional* parallel programming.

Maybe I should elaborate on my original motivation for this collection of ray tracers.  The original motivation for all this was [a course I taught on Parallel Functional Programming](https://github.com/diku-dk/pfp-e2019-pub), where I had a part on Parallel Haskell.  I ended up spending most of my lecture on the pitfalls of parallelism in Haskell, and the resulting performance ended up being rather middling, without any clear reason (short of digging into the compiler output and no longer reasoning in terms of the language).  The students did not find it very motivating, and neither did I.  I wanted to find a language that would allow me to focus on the core principles of deterministic task-parallellism, and have the performance feel commensurate with the quality of the parallelisation, not with the amount of obscure low-level optimisation.

Right now, I think F# looks like the most promising candidate, and the students already know F# from previous courses.  MPL is a close second, not so much because of the performance, but because the course is research-based, and MPL has some very nice implementation papers to go with it.
